### ISSUE TITLE
Replace momentjs with dayjs

### ISSUE THREAD

**Issue by david-poindexter** [dnnsoftware/Dnn.Platform#3875]
## Description of problem
We are currently using Moment.js in various areas of DNN.  

## Description of solution
We should evaluate replacing with `dayjs` (which is much more lightweight and has a similar API).

The following are all the areas that need to be updated.  We'll use this as a checklist for PRs (one PR per area).

### Admin Experience
* [x] Dnn.EditBar.UI #5082 
* [x] Dnn.PersonaBar.UI #5107 
* [x] Dnn.React.Common #4466 
* [x] AdminLogs.Web #4464 
* [x] Pages.Web #4463 
* [x] Prompt.Web #4465
* [x] Roles.Web #4462
* [x] Servers.Web #4104
* [x] SiteImportExport.Web #4461
* [x] Sites.Web #4459 
* [x] Users.Web #4108

### Platform
* [x] DotNetNuke.Web #5083
* [x] Website #5083

## Description of alternatives considered
n/a

## Screenshots
n/a

## Additional context
We could go from approximately 18.2 KB to 2 KB.

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
Yep, but... We need to test for calendars in other cultures, i know this is used some places and there has already been some reported issues about it. Other than that I totally vote for that.

**Comment by bdukes** [comment]
https://momentjs.com/docs/#/-project-status/
>We now generally consider Moment to be a legacy project in maintenance mode. It is not _dead_, but it is indeed _done_.

**Comment by david-poindexter** [comment]
@bdukes thanks for documenting that here.  I am going to go ahead and start seeing what I can do to replace it with dayjs.  I am hoping it will be a fairly smooth transition.  I have experienced this in several other projects so far and I am hoping this one to be the same.

**Comment by bdukes** [comment]
@david-poindexter do you want this pinned?

**Comment by david-poindexter** [comment]
That would be great- thanks @bdukes

**Comment by david-poindexter** [comment]
I have discovered we use a third-party JS DatePicker in our `DnnDatePicker` control, as well as within the PersonaBar.  The third-party JS DatePicker, [Pikaday](https://github.com/Pikaday/Pikaday), unfortunately depends on `momentjs`.  Short of replacing this date picker, I think the best thing we can do at this point is to simply upgrade `momentjs` to the latest release.  We are using v2.5.1 in `DnnDatePicker` and v2.8.1.  v2.29.2 was just released 7 days ago.

Thoughts @dnnsoftware/approvers?

**Comment by valadas** [comment]
My vote is to go for it
