### ISSUE TITLE
[Enhancement]: Make a test issue to see how issue forms work

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#5679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of problem

We just implemented issue forms and this is to test it out to see how a produce issue looks like.

### Description of solution

Doing this test and viewing the issue created.

<img src="https://media1.giphy.com/media/7MZ0v9KynmiSA/giphy.gif"/>

### Description of alternatives considered

Not testing it...

<img src="https://media4.giphy.com/media/fikcKja7O7MtzXzvQy/giphy.gif"/>

### Do you be plan to contribute code for this enhancement?

- [ ] Yes

### Would you be interested in sponsoring this enhancement?

- [ ] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
```[tasklist]
### Tasks
- [x] Thing 1
- [ ] https://github.com/dnnsoftware/Dnn.Platform/issues/5680
```
